[build]
  command = "yarn build && yarn export"
  publish = "out"

[context.branch-deploy]
  command = "sed -i s/AUTH_PLACEHOLDER/${AUTH_HEADER}/g netlifyheaders && yarn build && yarn export && cp netlifyheaders out/_headers"
